################################################################################################################################################################

# @project        Raspberry Pi Setup
# @file           playbook/setup.yml
# @author         Lucas Brémond <lucas.bremond@gmail.com>
# @license        MIT License

################################################################################################################################################################

- name: Configure all servers
  hosts: common
  roles:
    - common

# - name: Configure DNS servers
#   hosts: dns
#   roles:
#     - dns

# - name: Configure VPN servers
#   hosts: vpn
#   roles:
#     - vpn

# - name: Configure RTL-SDR servers
#   hosts: rtl-sdr
#   roles:
#     - rtl-sdr

################################################################################################################################################################