################################################################################################################################################################

# @project        Raspberry Pi Setup
# @file           roles/vpn/tasks/install.yml
# @author         Lucas Brémond <lucas.bremond@gmail.com>
# @license        MIT License

################################################################################################################################################################

- name: Install VPN utilities
  apt:
    name: ['openswan', 'xl2tpd', 'ppp', 'lsof', 'iptables']
    state: latest
    update_cache: yes
  become: yes

################################################################################################################################################################