################################################################################################################################################################

# @project        Raspberry Pi Setup
# @file           roles/common/tasks/apt.yml
# @author         Lucas Brémond <lucas.bremond@gmail.com>
# @license        MIT License

################################################################################################################################################################

- name: "Update APT package cache"
  action: apt update_cache=yes
  become: yes

- name: "Upgrade APT to the lastest packages"
  action: apt upgrade=safe
  become: yes

################################################################################################################################################################