################################################################################################################################################################

# @project        Raspberry Pi Setup
# @file           roles/common/tasks/locale.yml
# @author         Lucas Brémond <lucas.bremond@gmail.com>
# @license        MIT License

################################################################################################################################################################

- name: Add locale
  locale_gen: name={{ item }} state=present
  with_items: "{{ locale.locales }}"
  become: yes

- name: Set default locale
  template: src=../templates/default/locale.j2 dest=/etc/default/locale
  become: yes

################################################################################################################################################################